# Generated by Django 4.1.3 on 2022-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tuman_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijtimoiyhimoya',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
