# Generated by Django 4.1.3 on 2022-12-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_ijtimoiyhimoya_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='doimiy_yashash_manzili',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tuman'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ijtimoiy_himoya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.ijtimoiyhimoya'),
        ),
    ]
