# Generated by Django 4.1.3 on 2022-12-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_person_doimiy_yashash_manzili_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hozirgi_yashash_manzili',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='doimiy_yashash_manzili',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ijtimoiy_himoya',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
