# Generated by Django 4.1.3 on 2022-12-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_person_hozirgi_yashash_manzili_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ijtimoiyhimoya',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tuman',
            name='slug',
        ),
    ]
