# Generated by Django 4.1.3 on 2022-12-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_person_nogironligi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='doimiy_yashash_manzili',
            new_name='tuman',
        ),
    ]
