# Generated by Django 4.1.3 on 2022-12-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_doimiy_yashash_manzili_person_tuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nogironlik_raqami',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
