# Generated by Django 4.1.3 on 2022-12-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_person_nogironlik_raqami'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': [models.OrderBy(models.F('created'), descending=True)]},
        ),
        migrations.AlterField(
            model_name='person',
            name='ijtimoiy_himoya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.ijtimoiyhimoya'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tuman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.tuman'),
        ),
    ]
