# Generated by Django 4.1.3 on 2022-12-07 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_person_ijtimoiy_himoya_remove_person_tuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ijtimoiy_himoya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.ijtimoiyhimoya'),
        ),
        migrations.AddField(
            model_name='person',
            name='tuman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.tuman'),
        ),
    ]
