# Generated by Django 4.1.3 on 2022-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_person_ijtimoiy_himoya_person_tuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ijtimoiy_himoya',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tuman',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
