# Generated by Django 4.1.3 on 2022-12-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_person_ijtimoiy_himoya_alter_person_tuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
