# Generated by Django 4.1.3 on 2022-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tavsif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
